/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LCE;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.FileWriter;
import java.util.Arrays;
import java.util.List;
import java.util.Properties;

class AppTest {
    @Test
    void testApp() {
        int[] target = new int[] { 1, 3, 5, 1, 6 };
        int[] tester = new int[] { 1, 5, 3, 1, 4 };
        LCS lcs = new LCS();
        assertArrayEquals(new int[] { 1, 3, 1 }, lcs.longestCommonSubsequenceOfIntegerArray(target, tester));
    }

    @Test
    void testPreprocess() {
        // Arrange
        App app = new App();
        List<String> inputList = Arrays.asList("1,John,Doe,30,Male", "2,Jane,Smith,25,Female");

        // Act
        List<String[]> result = app.commaSeperatedLineToStringArray(inputList);

        // Assert
        assertEquals(2, result.size());

        assertArrayEquals(new String[] { "1", "John", "Doe", "30", "Male" }, result.get(0));
        assertArrayEquals(new String[] { "2", "Jane", "Smith", "25", "Female" }, result.get(1));
    }


    @Test
    void testcommaSeperatedLineToStringArray() {

        App app = new App();

        List<String> result = Arrays.asList("567823eb81b7f253662e09a119175b75428abf19,2f9c8ac25ba634affe366ce55eb3f9e969e71ae3,launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java,launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java,https://github.com/apache/spark,SPARK");
        List<String[]> return_split = app.commaSeperatedLineToStringArray(result);
        assertEquals(1, return_split.size());
        assertArrayEquals(new String[] { "567823eb81b7f253662e09a119175b75428abf19", "2f9c8ac25ba634affe366ce55eb3f9e969e71ae3", "launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java", "launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java", "https://github.com/apache/spark", "SPARK"}, return_split.get(0));

        result = Arrays.asList("567823eb81b7f253662e09a119175b75428abf19,2f9c8ac25ba634affe366ce55eb3f9e969e71ae3,launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java,launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java,https://github.com/apache/spark,SPARK,67,67");
        return_split = app.commaSeperatedLineToStringArray(result);

        assertEquals(1, return_split.size());
        assertArrayEquals(new String[] { "567823eb81b7f253662e09a119175b75428abf19", "2f9c8ac25ba634affe366ce55eb3f9e969e71ae3", "launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java", "launcher/src/test/java/org/apache/spark/launcher/SparkSubmitCommandBuilderSuite.java", "https://github.com/apache/spark", "SPARK", "67", "67"}, return_split.get(0));

    }

    @Test
    void testLoadProperties() {
        // Arrange
        App app = new App();
        String testFilePath = "test.properties";

        // Create a temporary properties file for testing
        try (FileWriter fileWriter = new FileWriter(testFilePath)) {
            fileWriter.write("key1=value1\nkey2=value2");
        } catch (Exception e) {
            fail("Failed to create a test properties file.");
        }

        // Act
        Properties loadedProperties = app.loadProperties(testFilePath);

        // Assert
        assertNotNull(loadedProperties, "Loaded properties should not be null.");
        assertEquals("value1", loadedProperties.getProperty("key1"), "Incorrect value for key1");
        assertEquals("value2", loadedProperties.getProperty("key2"), "Incorrect value for key2");

        // Clean up - delete the temporary properties file
        File testFile = new File(testFilePath);
        if (!testFile.delete()) {
            System.out.println("Warning: Test properties file deletion failed.");
        }
    }


}
